apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-jetstack
  labels:
    alias: cm
    selector: "feat/cert-manager=jetstack/cert-manager"
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: "feat/cert-manager"
              operator: In
              values: ["jetstack/cert-manager"]
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.x
        helm:
          valuesObject:
            crds:
              enabled: true