apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            # Either the label is missing, or it’s not "false"
            - key: app/cert-manager
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: oci://quay.io/jetstack/charts/cert-manager
        targetRevision: v1.*
        helm:
          valuesObject:
            crds:
              enabled: true