apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-jetstack
  annotations:
    description: Certificate Manager for Kubernetes
    variables: |
      optionnal email Email address for Let's Encrypt account
  labels:
    alias: cm
    feat: cert-manager
    flavor: jetstack
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: "feat/cert-manager"
              operator: In
              values: ["jetstack"]
  goTemplate: true
  template:
    metadata:
      name: 'cert-manager-jetstack'
      labels:
        feat: cert-manager
        flavor: jetstack
    spec:
      project: default
      destination:
        server: '{{ .server }}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.x
        helm:
          #valuesObject:
          values: |
            crds:
              enabled: true
            {{- with (index .metadata.annotations "feat/cert-manager.email") }}
            extraObjects:
              - |
                apiVersion: cert-manager.io/v1
                kind: ClusterIssuer
                metadata:
                  name: letsencrypt-prod
                spec:
                  acme:
                    server: https://acme-v02.api.letsencrypt.org/directory
                    email: {{ . }}
                    privateKeySecretRef:
                      name: letsencrypt-prod
                    solvers:
                    - http01:
                        ingress: {}
              - |
                apiVersion: cert-manager.io/v1
                kind: ClusterIssuer
                metadata:
                  name: letsencrypt-staging
                spec:
                  acme:
                    server: https://acme-staging-v02.api.letsencrypt.org/directory
                    email: {{ . }}
                    privateKeySecretRef:
                      name: letsencrypt-staging
                    solvers:
                    - http01:
                        ingress: {}
            {{- end }}