apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: app/cert-manager
              operator: Exists
            - key: app/cert-manager
              operator: In
              values: ["true"]
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.x
        helm:
          valuesObject:
            crds:
              enabled: true