apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-path-storage
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: app/local-path-storage
              operator: Exists
            - key: app/local-path-storage
              operator: In
              values: ["true"]
  template:
    metadata:
      name: '{{name}}-local-path-storage'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: local-path-storage
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
      - repoURL: https://github.com/AlexisDucastel/argocd-generic-k8s.git
        targetRevision: main
        path: config/local-path-storage/